[package]
name = "api-database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
api-core = { workspace = true, features = ["serde", "surrealdb"] }
serde.workspace = true
surrealdb.workspace = true
thiserror.workspace = true
tracing.workspace = true
