on:
  push:
    branches: [master]
  pull_request:
name: rust

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    name: ubuntu / stable / check
    steps:
      - uses: actions/checkout@v4
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: cargo check
        run: cargo check

  os-check:
    runs-on: ${{ matrix.os }}
    env:
      DB_USER: ${{ secrets.TEST_DATABASE_USERNAME }}
      DB_URL: ${{ secrets.TEST_DATABASE_URL }}
      DB_PASS: ${{ secrets.TEST_DATABASE_PASSWORD }}
      DB_NAME: ${{ secrets.TEST_DATABASE_NAME }}
      DB_NS: ${{ secrets.TEST_DATABASE_NAMESPACE }}

    name: ${{ matrix.os }} / stable
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - name: Get sample dataset
        uses: actions/checkout@v4
        with:
          repository: sellershut/db-categories
          token: ${{ secrets.PAT_CATEGORIES_DATASET }}
          path: .dataset-categories
      - name: install surreal
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://install.surrealdb.com | sh
          surreal start --log trace --auth --user $DB_USER --pass $DB_PASS memory &
      - name: import dataset
        run: |
          surreal import --conn $DB_URL --user $DB_USER --pass $DB_PASS --ns $DB_NS --db $DB_NAME .dataset-categories/categories.surql
      - uses: actions/checkout@v4
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - name: cargo test --workspace
        run: cargo test --no-run --workspace --locked --all-features --all-targets

  coverage:
    runs-on: ubuntu-latest
    env:
      DB_USER: ${{ secrets.TEST_DATABASE_USERNAME }}
      DB_URL: ${{ secrets.TEST_DATABASE_URL }}
      DB_PASS: ${{ secrets.TEST_DATABASE_PASSWORD }}
      DB_NAME: ${{ secrets.TEST_DATABASE_NAME }}
      DB_NS: ${{ secrets.TEST_DATABASE_NAMESPACE }}

    name: ubuntu / stable / coverage
    steps:
      - name: Get sample dataset
        uses: actions/checkout@v4
        with:
          repository: sellershut/db-categories
          token: ${{ secrets.PAT_CATEGORIES_DATASET }}
          path: .dataset-categories
      - name: install surreal
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://install.surrealdb.com | sh
          surreal start --log trace --auth --user $DB_USER --pass $DB_PASS memory &
      - name: import dataset
        run: |
          surreal import --conn $DB_URL --user $DB_USER --pass $DB_PASS --ns $DB_NS --db $DB_NAME .dataset-categories/categories.surql
      - uses: actions/checkout@v4
      - name: Install stable
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: cargo install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: cargo llvm-cov
        run: cargo llvm-cov --workspace --locked --all-features --lcov --output-path lcov.info
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
